name: dart_frog_backend
description: An new Dart Frog application
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^0.2.0
  jaspr: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  jaspr_builder: ^0.3.0
  lints: ^2.1.0
