name: {{name}}
description: A classic web app using separate html, css and dart files with ssr & manual client hydration.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^{{jasprCoreVersion}}

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  jaspr_builder: ^{{jasprBuilderVersion}}
  lints: ^2.1.0
