name: jaspr_basic_template
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^0.13.4
  jaspr: ^0.2.0
  jaspr_riverpod: ^0.1.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^1.0.0

dependency_overrides:
  jaspr:
    path: ../../../../packages/jaspr
  jaspr_riverpod:
    path: ../../../../packages/jaspr_riverpod
