on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test_win.yml'
      - 'packages/**'
  push:
    branches:
      - wintest
    paths:
      - '.github/workflows/test_win.yml'
      - 'packages/**'

name: Test Pipeline

jobs:
  test1:
    name: Global Cli Test
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1.3

      - name: Run
        run: |
          dart create -t cli cli_test
          echo "executables:\n  cli_test:" >> cli_test/pubspec.yaml
          dart pub global activate cli_test --source=path
          dart pub global run cli_test --version

  test2:
    name: Standalone Cli Test
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1.3

      - name: Run
        run: |
          dart create -t cli cli_test
          echo "executables:\n  cli_test:\n" >> cli_test/pubspec.yaml
          type cli_test/pubspec.yaml
          dart pub global activate cli_test --source=path
          cli_test --version
