on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test_win.yml'
      - 'packages/**'
  push:
    branches:
      - wintest
    paths:
      - '.github/workflows/test_win.yml'
      - 'packages/**'

name: Test Pipeline

jobs:
  test:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1.3
      - uses: subosito/flutter-action@v2

      - name: Run
        run: |
          dart pub global activate packages/jaspr_cli --source=path
          cd examples/package_riverpod
          dart pub global run jaspr_cli:jaspr doctor

  test2:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1.3
      - uses: subosito/flutter-action@v2

      - name: Run
        run: |
          dart pub global activate packages/jaspr_cli --source=path
          cd examples/package_riverpod
          jaspr doctor
